// <auto-generated />
using System;
using KrediHesaplamaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrediHesaplamaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723112426_AddHesaplamaTable")]
    partial class AddHesaplamaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KrediHesaplamaAPI.Models.Hesaplama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AylikOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Faiz")
                        .HasColumnType("float");

                    b.Property<DateTime>("HesaplamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KrediTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemePlaniJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToplamOdeme")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hesaplamalar");
                });

            modelBuilder.Entity("KrediHesaplamaAPI.Models.KrediUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FaizOrani")
                        .HasColumnType("float");

                    b.Property<double>("MaxTutar")
                        .HasColumnType("float");

                    b.Property<int>("MaxVade")
                        .HasColumnType("int");

                    b.Property<double>("MinTutar")
                        .HasColumnType("float");

                    b.Property<int>("MinVade")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KrediUrunleri");
                });
#pragma warning restore 612, 618
        }
    }
}
